(1) SELECT LEN(NULL),LEN('  hello '),LEN('');


(2) SELECT UPPER('bhavya'),LOWER('BHAVYA');


(3) SELECT SUBSTRING('Bhavya',1,3); 


(4) SELECT SUBSTRING('BHAVYABARAI',3,10);


(5) SELECT REPLACE('abc123efg','123','XYZ'),
           REPLACE('abcabcabc','c',5);


(6) SELECT ASCII('a'),ASCII('A'),ASCII('z'),ASCII('Z'),ASCII(0),ASCII(9);


(7) SELECT CHAR(97),CHAR(65),CHAR(122),CHAR(90),CHAR(48),CHAR(57);


(8) SELECT LTRIM('       hello world    ');


(9) SELECT RTRIM('hello world     ');


(10) SELECT LEFT('SQL SERVER',4),RIGHT('SQL SERVER',5);


(11) SELECT CAST('1234.56' AS FLOAT);


(12) SELECT CONVERT (INT,10.58);


(13) SELECT SPACE(10) + 'Bhavya';


(14) SELECT 'BHAVYA' + 'BARAI';
     SELECT CONCAT('BHAVYA','BARAI');


(15) SELECT REVERSE('DARSHAN');


(16) SELECT REPLICATE('BHAVYA ',3);


(17) SELECT STUFF('SQL SERVER',1,3,'HTML');


(18) SELECT COALESCE(NULL,NULL,'SQL',NULL,'CSS');


(19) SELECT ISNUMERIC('ABC');
	SELECT ISNUMERIC(12);


(20) SELECT CHARINDEX('T','customer');