CREATE TABLE STUDENT3
(
RNO INT,
NAME VARCHAR(50),
BRANCH VARCHAR(50)
);

INSERT INTO STUDENT3
  VALUES(101,'RAJU','CE'),
        (102,'AMIT','CE'),
		(103,'RAJU','ME'),
		(104,'NEHA','EC'),
		(105,'MEERA','EE'),
		(106,'MAHESH','ME')

CREATE TABLE RESULT
(
RNO INT,
SPI DECIMAL(4,2)
);